### ISSUE TITLE
Question: How can I receive packets when I don't know the content?

### ISSUE THREAD

**Issue by afeno** [ElephantIO/elephant.io#17]
Hello,

I am new with websockets/IOSockets. I have a bit on experience using IOSockets in Node and Python but I need to use php as a IOSocket client and elephant.io seems to be what I am looking for.

The question that I have is about how to receive messages when I don't know the content. (any message)
`$client->wait('blablabla') ` will wait until "blablabla" is receveid but how can I get ANY messages and then check what the message is?

Should I use `drain `for that? Is that correct?

Thank you!

**Comment by tohenk** [comment]
Yes, you can use `drain()`.

**Comment by afeno** [comment]
Thanks!
