### ISSUE TITLE
Option "'reuse_connection' => false" doesn't work since 4.6.0

### ISSUE THREAD

**Issue by kaliberx** [ElephantIO/elephant.io#22]
For some reasons our SocketIO server (based on https://github.com/mrniko/netty-socketio) closes connection when using polling transport and we are getting "Broken pipe" error. Therefore we disabled reusing connection to make it working.
Unfortunately it doesn't work since 4.6.0 and despite "'reuse_connection' => false" we are still getting "Broken pipe" error.

Possible fix is to move "$this->createStream();" at the beginning of the method \ElephantIO\Engine\SocketIO::_transport()

**Comment by tohenk** [comment]
Fixed in f3f9d9989cb264bac5c4655be7d8acc0466c1d8e.
