### ISSUE TITLE
get_class(): Argument #1 ($object) must be of type object, string given

### ISSUE THREAD

**Issue by roniedev01** [ElephantIO/elephant.io#28]
#With the latest version of this package I have got this error. It should be fix. My project is running with PHP 8.2 and Yii2 2.0.51.

 in /home/example/public_html/vendor/elephantio/elephant.io/src/Util.phpat line 196
![elephatio_error](https://github.com/user-attachments/assets/c35a9db8-08b2-469d-b535-94b25a60f4ec)

Please update the package and inform us.

Fix should be like below:----

  /**
     * Get Composer autoloader instance.
     *
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getComposer()
    {
        if ($autoloaders = spl_autoload_functions()) {
            foreach ($autoloaders as $autoload) {
                if (is_array($autoload)) {
                    $class = $autoload[0];
                    if (is_object($class) && 'Composer\Autoload\ClassLoader' === get_class($class)) {
                        return $class;
                    }
                }
            }
        }
    }

**Comment by tohenk** [comment]
Fixed in 51642d349f968be9b7cc5f57706ac44431b20685.
